package cc.ardennehiking.app.service;

import java.util.Collection;
import java.util.HashMap;

//info from http://www.geonames.org/export/ws-overview.html
public class Config {


    public static final String geoNamesUserString = "username=djodjo";
    public static final String geoNamesBaseUrl = "http://api.geonames.org/";
    public static final String geoNamesUriSearch = "/searchJSON";
    public static final String geoNamesUriWikiBBSearch = "/wikipediaBoundingBoxJSON";
    public static final String geoNamesUriOSMNearby = "/findNearbyPOIsOSMJSON";

    public static final String osmOverpassBaseUrl = "http://overpass.osm.rambler.ru/cgi/interpreter?data=[out:json];node";



    public static final String defParams = "?maxRows=500&formatted=true&style=full&" + geoNamesUserString;
    public static final String defParams2 = "?maxRows=50&formatted=true&style=full&" + geoNamesUserString;

    public static String getBoundigboxParams(double north, double south, double east, double west) {
        return "&north=" + north + "&south=" + south + "&east=" + east + "&west=" + west;
    }

    public static String getOverpassQuery(Collection<String> types) {
        StringBuilder sb =  new StringBuilder();
        for(String type:types) {
            sb.append("["+type+"]");
        }
        return sb.toString();
    }

    public static HashMap<String, String> titleMap = new HashMap<>();
    public static HashMap<String, String> descMap = new HashMap<>();

    static {
        titleMap.put("A.ADM1", "first-order administrative division"); descMap.put("A.ADM1", "a primary administrative division of a country, such as a state in the United States");
        titleMap.put("A.ADM1H", "historical first-order administrative division"); descMap.put("A.ADM1H", "a former first-order administrative division");
        titleMap.put("A.ADM2", "second-order administrative division"); descMap.put("A.ADM2", "a subdivision of a first-order administrative division");
        titleMap.put("A.ADM2H", "historical second-order administrative division"); descMap.put("A.ADM2H", "a former second-order administrative division");
        titleMap.put("A.ADM3", "third-order administrative division"); descMap.put("A.ADM3", "a subdivision of a second-order administrative division");
        titleMap.put("A.ADM3H", "historical third-order administrative division"); descMap.put("A.ADM3H", "a former third-order administrative division");
        titleMap.put("A.ADM4", "fourth-order administrative division"); descMap.put("A.ADM4", "a subdivision of a third-order administrative division");
        titleMap.put("A.ADM4H", "historical fourth-order administrative division"); descMap.put("A.ADM4H", "a former fourth-order administrative division");
        titleMap.put("A.ADM5", "fifth-order administrative division"); descMap.put("A.ADM5", "a subdivision of a fourth-order administrative division");
        titleMap.put("A.ADMD", "administrative division"); descMap.put("A.ADMD", "an administrative division of a country, undifferentiated as to administrative level");
        titleMap.put("A.ADMDH", "historical administrative division "); descMap.put("A.ADMDH", "a former administrative division of a political entity, undifferentiated as to administrative level");
        titleMap.put("A.LTER", "leased area"); descMap.put("A.LTER", "a tract of land leased to another country, usually for military installations");
        titleMap.put("A.PCL", "political entity"); descMap.put("A.PCL", "");
        titleMap.put("A.PCLD", "dependent political entity");     descMap.put("A.PCLD", "");
        titleMap.put("A.PCLF","freely associated state"); descMap.put("A.PCLF","");
        titleMap.put("A.PCLH", "historical political entity"); descMap.put("A.PCLH", "a former political entity");
        titleMap.put("A.PCLI", "independent political entity"); descMap.put("A.PCLI","");
        titleMap.put("A.PCLIX", "section of independent political entity"); descMap.put("A.PCLIX","");
        titleMap.put("A.PCLS", "semi-independent political entity"); descMap.put("A.PCLS","");
        titleMap.put("A.PRSH", "parish"); descMap.put("A.PRSH", "an ecclesiastical district");
        titleMap.put("A.TERR", "territory"); descMap.put("A.TERR","");
        titleMap.put("A.ZN", "zone"); descMap.put("A.ZN","");
        titleMap.put("A.ZNB", "buffer zone"); descMap.put("A.ZNB", "a zone recognized as a buffer between two nations in which military presence is minimal or absent");
        titleMap.put("H.AIRS", "seaplane landing area"); descMap.put("H.AIRS", "a place on a waterbody where floatplanes land and take off");
        titleMap.put("H.ANCH", "anchorage"); descMap.put("H.ANCH", "an area where vessels may anchor");
        titleMap.put("H.BAY", "bay"); descMap.put("H.BAY", "a coastal indentation between two capes or headlands, larger than a cove but smaller than a gulf");
        titleMap.put("H.BAYS", "bays"); descMap.put("H.BAYS", "coastal indentations between two capes or headlands, larger than a cove but smaller than a gulf");
        titleMap.put("H.BGHT", "bight(s)"); descMap.put("H.BGHT", "an open body of water forming a slight recession in a coastline");
        titleMap.put("H.BNK", "bank(s)"); descMap.put("H.BNK", "an elevation, typically located on a shelf, over which the depth of water is relatively shallow but sufficient for most surface navigation");
        titleMap.put("H.BNKR", "stream bank"); descMap.put("H.BNKR", "a sloping margin of a stream channel which normally confines the stream to its channel on land");
        titleMap.put("H.BNKX", "section of bank"); descMap.put("H.BNKX","");
        titleMap.put("H.BOG", "bog(s)"); descMap.put("H.BOG", "a wetland characterized by peat forming sphagnum moss, sedge, and other acid-water plants");
        titleMap.put("H.CAPG", "icecap"); descMap.put("H.CAPG", "a dome-shaped mass of glacial ice covering an area of mountain summits or other high lands; smaller than an ice sheet");
        titleMap.put("H.CHN", "channel"); descMap.put("H.CHN", "the deepest part of a stream, bay, lagoon, or strait, through which the main current flows");
        titleMap.put("H.CHNL", "lake channel(s)"); descMap.put("H.CHNL", "that part of a lake having water deep enough for navigation between islands, shoals, etc.");
        titleMap.put("H.CHNM", "marine channel"); descMap.put("H.CHNM", "that part of a body of water deep enough for navigation through an area otherwise not suitable");
        titleMap.put("H.CHNN", "navigation channel"); descMap.put("H.CHNN", "a buoyed channel of sufficient depth for the safe navigation of vessels");
        titleMap.put("H.CNFL", "confluence"); descMap.put("H.CNFL", "a place where two or more streams or intermittent streams flow together");
        titleMap.put("H.CNL", "canal"); descMap.put("H.CNL", "an artificial watercourse");
        titleMap.put("H.CNLA", "aqueduct"); descMap.put("H.CNLA", "a conduit used to carry water");
        titleMap.put("H.CNLB", "canal bend"); descMap.put("H.CNLB", "a conspicuously curved or bent section of a canal");
        titleMap.put("H.CNLD", "drainage canal"); descMap.put("H.CNLD", "an artificial waterway carrying water away from a wetland or from drainage ditches");
        titleMap.put("H.CNLI", "irrigation canal"); descMap.put("H.CNLI", "a canal which serves as a main conduit for irrigation water");
        titleMap.put("H.CNLN", "navigation canal(s)"); descMap.put("H.CNLN", "a watercourse constructed for navigation of vessels");
        titleMap.put("H.CNLQ",	"abandoned canal"); descMap.put("H.CNLQ","");
        titleMap.put("H.CNLSB", "underground irrigation canal(s)"); descMap.put("H.CNLSB", "a gently inclined underground tunnel bringing water for irrigation from aquifers");
        titleMap.put("H.CNLX",	"section of canal"); descMap.put("H.CNLX","");
        titleMap.put("H.COVE", "cove(s)"); descMap.put("H.COVE", "a small coastal indentation, smaller than a bay");
        titleMap.put("H.CRKT", "tidal creek(s)"); descMap.put("H.CRKT", "a meandering channel in a coastal wetland subject to bi-directional tidal currents");
        titleMap.put("H.CRNT", "current"); descMap.put("H.CRNT", "a horizontal flow of water in a given direction with uniform velocity");
        titleMap.put("H.CUTF", "cutoff"); descMap.put("H.CUTF", "a channel formed as a result of a stream cutting through a meander neck");
        titleMap.put("H.DCK", "dock(s)"); descMap.put("H.DCK", "a waterway between two piers, or cut into the land for the berthing of ships");
        titleMap.put("H.DCKB", "docking basin"); descMap.put("H.DCKB", "a part of a harbor where ships dock");
        titleMap.put("H.DOMG", "icecap dome"); descMap.put("H.DOMG", "a comparatively elevated area on an icecap");
        titleMap.put("H.DPRG", "icecap depression"); descMap.put("H.DPRG", "a comparatively depressed area on an icecap");
        titleMap.put("H.DTCH", "ditch"); descMap.put("H.DTCH", "a small artificial watercourse dug for draining or irrigating the land");
        titleMap.put("H.DTCHD", "drainage ditch"); descMap.put("H.DTCHD", "a ditch which serves to drain the land");
        titleMap.put("H.DTCHI", "irrigation ditch"); descMap.put("H.DTCHI", "a ditch which serves to distribute irrigation water");
        titleMap.put("H.DTCHM", "ditch mouth(s)"); descMap.put("H.DTCHM", "an area where a drainage ditch enters a lagoon, lake or bay");
        titleMap.put("H.ESTY", "estuary"); descMap.put("H.ESTY", "a funnel-shaped stream mouth or embayment where fresh water mixes with sea water under tidal influences");
        titleMap.put("H.FISH", "fishing area"); descMap.put("H.FISH", "a fishing ground, bank or area where fishermen go to catch fish");
        titleMap.put("H.FJD", "fjord"); descMap.put("H.FJD", "a long, narrow, steep-walled, deep-water arm of the sea at high latitudes, usually along mountainous coasts");
        titleMap.put("H.FJDS", "fjords"); descMap.put("H.FJDS", "long, narrow, steep-walled, deep-water arms of the sea at high latitudes, usually along mountainous coasts");
        titleMap.put("H.FLLS", "waterfall(s)"); descMap.put("H.FLLS", "a perpendicular or very steep descent of the water of a stream");
        titleMap.put("H.FLLSX",	"section of waterfall(s)"); descMap.put("H.FLLSX","");
        titleMap.put("H.FLTM", "mud flat(s)"); descMap.put("H.FLTM", "a relatively level area of mud either between high and low tide lines, or subject to flooding");
        titleMap.put("H.FLTT", "tidal flat(s)"); descMap.put("H.FLTT", "a large flat area of mud or sand attached to the shore and alternately covered and uncovered by the tide");
        titleMap.put("H.GLCR", "glacier(s)"); descMap.put("H.GLCR", "a mass of ice, usually at high latitudes or high elevations, with sufficient thickness to flow away from the source area in lobes, tongues, or masses");
        titleMap.put("H.GULF", "gulf"); descMap.put("H.GULF", "a large recess in the coastline, larger than a bay");
        titleMap.put("H.GYSR", "geyser"); descMap.put("H.GYSR", "a type of hot spring with intermittent eruptions of jets of hot water and steam");
        titleMap.put("H.HBR", "harbor(s)"); descMap.put("H.HBR", "a haven or space of deep water so sheltered by the adjacent land as to afford a safe anchorage for ships");
        titleMap.put("H.HBRX", "section of harbor"); descMap.put("H.HBRX","");
        titleMap.put("H.INLT", "inlet"); descMap.put("H.INLT", "a narrow waterway extending into the land, or connecting a bay or lagoon with a larger body of water");
        titleMap.put("H.INLTQ", "former inlet"); descMap.put("H.INLTQ", "an inlet which has been filled in, or blocked by deposits");
        titleMap.put("H.LBED", "lake bed(s)"); descMap.put("H.LBED", "a dried up or drained area of a former lake");
        titleMap.put("H.LGN", "lagoon"); descMap.put("H.LGN", "a shallow coastal waterbody, completely or partly separated from a larger body of water by a barrier island, coral reef or other depositional feature");
        titleMap.put("H.LGNS", "lagoons"); descMap.put("H.LGNS", "shallow coastal waterbodies, completely or partly separated from a larger body of water by a barrier island, coral reef or other depositional feature");
        titleMap.put("H.LGNX",	"section of lagoon"); descMap.put("H.LGNX","");
        titleMap.put("H.LK", "lake"); descMap.put("H.LK", "a large inland body of standing water");
        titleMap.put("H.LKC", "crater lake"); descMap.put("H.LKC", "a lake in a crater or caldera");
        titleMap.put("H.LKI", "intermittent lake"); descMap.put("H.LKI","");
        titleMap.put("H.LKN", "salt lake"); descMap.put("H.LKN", "an inland body of salt water with no outlet");
        titleMap.put("H.LKNI",	"intermittent salt lake"); descMap.put("H.LKNI","");
        titleMap.put("H.LKO", "oxbow lake"); descMap.put("H.LKO", "a crescent-shaped lake commonly found adjacent to meandering streams");
        titleMap.put("H.LKOI",	"intermittent oxbow lake"); descMap.put("H.LKOI","");
        titleMap.put("H.LKS", "lakes"); descMap.put("H.LKS", "large inland bodies of standing water");
        titleMap.put("H.LKSB", "underground lake"); descMap.put("H.LKSB", "a standing body of water in a cave");
        titleMap.put("H.LKSC", "crater lakes"); descMap.put("H.LKSC", "lakes in a crater or caldera");
        titleMap.put("H.LKSI",	"intermittent lakes"); descMap.put("H.LKSI","");
        titleMap.put("H.LKSN", "salt lakes"); descMap.put("H.LKSN", "inland bodies of salt water with no outlet");
        titleMap.put("H.LKSNI", "intermittent salt lakes"); descMap.put("H.LKSNI","");
        titleMap.put("H.LKX", "section of lake"); descMap.put("H.LKX","");
        titleMap.put("H.MFGN", "salt evaporation ponds"); descMap.put("H.MFGN", "diked salt ponds used in the production of solar evaporated salt");
        titleMap.put("H.MGV", "mangrove swamp"); descMap.put("H.MGV", "a tropical tidal mud flat characterized by mangrove vegetation");
        titleMap.put("H.MOOR", "moor(s)"); descMap.put("H.MOOR", "an area of open ground overlaid with wet peaty soils");
        titleMap.put("H.MRSH", "marsh(es)"); descMap.put("H.MRSH", "a wetland dominated by grass-like vegetation");
        titleMap.put("H.MRSHN", "salt marsh"); descMap.put("H.MRSHN", "a flat area, subject to periodic salt water inundation, dominated by grassy salt-tolerant plants");
        titleMap.put("H.NRWS", "narrows"); descMap.put("H.NRWS", "a navigable narrow part of a bay, strait, river, etc.");
        titleMap.put("H.OCN", "ocean"); descMap.put("H.OCN", "one of the major divisions of the vast expanse of salt water covering part of the earth");
        titleMap.put("H.OVF", "overfalls"); descMap.put("H.OVF", "an area of breaking waves caused by the meeting of currents or by waves moving against the current");
        titleMap.put("H.PND", "pond"); descMap.put("H.PND", "a small standing waterbody");
        titleMap.put("H.PNDI", "intermittent pond"); descMap.put("H.PNDI","");
        titleMap.put("H.PNDN", "salt pond"); descMap.put("H.PNDN", "a small standing body of salt water often in a marsh or swamp, usually along a seacoast");
        titleMap.put("H.PNDNI", "intermittent salt pond(s)"); descMap.put("H.PNDNI","");
        titleMap.put("H.PNDS", "ponds"); descMap.put("H.PNDS", "small standing waterbodies");
        titleMap.put("H.PNDSF", "fishponds"); descMap.put("H.PNDSF", "ponds or enclosures in which fish are kept or raised");
        titleMap.put("H.PNDSI", "intermittent ponds"); descMap.put("H.PNDSI","");
        titleMap.put("H.PNDSN", "salt ponds"); descMap.put("H.PNDSN", "small standing bodies of salt water often in a marsh or swamp, usually along a seacoast");
        titleMap.put("H.POOL", "pool(s)"); descMap.put("H.POOL", "a small and comparatively still, deep part of a larger body of water such as a stream or harbor; or a small body of standing water");
        titleMap.put("H.POOLI", "intermittent pool"); descMap.put("H.POOLI","");
        titleMap.put("H.RCH", "reach"); descMap.put("H.RCH", "a straight section of a navigable stream or channel between two bends");
        titleMap.put("H.RDGG", "icecap ridge"); descMap.put("H.RDGG", "a linear elevation on an icecap");
        titleMap.put("H.RDST", "roadstead"); descMap.put("H.RDST", "an open anchorage affording less protection than a harbor");
        titleMap.put("H.RF", "reef(s)"); descMap.put("H.RF", "a surface-navigation hazard composed of consolidated material");
        titleMap.put("H.RFC", "coral reef(s)"); descMap.put("H.RFC", "a surface-navigation hazard composed of coral");
        titleMap.put("H.RFX", "section of reef"); descMap.put("H.RFX","");
        titleMap.put("H.RPDS", "rapids"); descMap.put("H.RPDS", "a turbulent section of a stream associated with a steep, irregular stream bed");
        titleMap.put("H.RSV", "reservoir(s)"); descMap.put("H.RSV", "an artificial pond or lake");
        titleMap.put("H.RSVI", "intermittent reservoir"); descMap.put("H.RSVI","");
        titleMap.put("H.RSVT", "water tank"); descMap.put("H.RSVT", "a contained pool or tank of water at, below, or above ground level");
        titleMap.put("H.RVN", "ravine(s)"); descMap.put("H.RVN", "a small, narrow, deep, steep-sided stream channel, smaller than a gorge");
        titleMap.put("H.SBKH", "sabkha(s)"); descMap.put("H.SBKH", "a salt flat or salt encrusted plain subject to periodic inundation from flooding or high tides");
        titleMap.put("H.SD", "sound"); descMap.put("H.SD", "a long arm of the sea forming a channel between the mainland and an island or islands; or connecting two larger bodies of water");
        titleMap.put("H.SEA", "sea"); descMap.put("H.SEA", "a large body of salt water more or less confined by continuous land or chains of islands forming a subdivision of an ocean");
        titleMap.put("H.SHOL", "shoal(s)"); descMap.put("H.SHOL", "a surface-navigation hazard composed of unconsolidated material");
        titleMap.put("H.SILL", "sill"); descMap.put("H.SILL", "the low part of an underwater gap or saddle separating basins, including a similar feature at the mouth of a fjord");
        titleMap.put("H.SPNG", "spring(s)"); descMap.put("H.SPNG", "a place where ground water flows naturally out of the ground");
        titleMap.put("H.SPNS", "sulphur spring(s)"); descMap.put("H.SPNS", "a place where sulphur ground water flows naturally out of the ground");
        titleMap.put("H.SPNT", "hot spring(s)"); descMap.put("H.SPNT", "a place where hot ground water flows naturally out of the ground");
        titleMap.put("H.STM", "stream"); descMap.put("H.STM", "a body of running water moving to a lower level in a channel on land");
        titleMap.put("H.STMA", "anabranch"); descMap.put("H.STMA", "a diverging branch flowing out of a main stream and rejoining it downstream");
        titleMap.put("H.STMB", "stream bend"); descMap.put("H.STMB", "a conspicuously curved or bent segment of a stream");
        titleMap.put("H.STMC", "canalized stream"); descMap.put("H.STMC", "a stream that has been substantially ditched, diked, or straightened");
        titleMap.put("H.STMD", "distributary(-ies)"); descMap.put("H.STMD", "a branch which flows away from the main stream, as in a delta or irrigation canal");
        titleMap.put("H.STMH", "headwaters"); descMap.put("H.STMH", "the source and upper part of a stream, including the upper drainage basin");
        titleMap.put("H.STMI", "intermittent stream"); descMap.put("H.STMI","");
        titleMap.put("H.STMIX", "section of intermittent stream"); descMap.put("H.STMIX","");
        titleMap.put("H.STMM", "stream mouth(s)"); descMap.put("H.STMM", "a place where a stream discharges into a lagoon, lake, or the sea");
        titleMap.put("H.STMQ", "abandoned watercourse"); descMap.put("H.STMQ", "a former stream or distributary no longer carrying flowing water, but still evident due to lakes, wetland, topographic or vegetation patterns");
        titleMap.put("H.STMS", "streams"); descMap.put("H.STMS", "bodies of running water moving to a lower level in a channel on land");
        titleMap.put("H.STMSB", "lost river"); descMap.put("H.STMSB", "a surface stream that disappears into an underground channel, or dries up in an arid area");
        titleMap.put("H.STMX", "section of stream"); descMap.put("H.STMX","");
        titleMap.put("H.STRT", "strait"); descMap.put("H.STRT", "a relatively narrow waterway, usually narrower and less extensive than a sound, connecting two larger bodies of water");
        titleMap.put("H.SWMP", "swamp"); descMap.put("H.SWMP", "a wetland dominated by tree vegetation");
        titleMap.put("H.SYSI", "irrigation system"); descMap.put("H.SYSI", "a network of ditches and one or more of the following elements: water supply, reservoir, canal, pump, well, drain, etc.");
        titleMap.put("H.TNLC", "canal tunnel"); descMap.put("H.TNLC", "a tunnel through which a canal passes");
        titleMap.put("H.WAD", "wadi"); descMap.put("H.WAD", "a valley or ravine, bounded by relatively steep banks, which in the rainy season becomes a watercourse; found primarily in North Africa and the Middle East");
        titleMap.put("H.WADB", "wadi bend"); descMap.put("H.WADB", "a conspicuously curved or bent segment of a wadi");
        titleMap.put("H.WADJ", "wadi junction"); descMap.put("H.WADJ", "a place where two or more wadies join");
        titleMap.put("H.WADM", "wadi mouth"); descMap.put("H.WADM", "the lower terminus of a wadi where it widens into an adjoining floodplain, depression, or waterbody");
        titleMap.put("H.WADS", "wadies"); descMap.put("H.WADS", "valleys or ravines, bounded by relatively steep banks, which in the rainy season become watercourses; found primarily in North Africa and the Middle East");
        titleMap.put("H.WADX", "section of wadi"); descMap.put("H.WADX","");
        titleMap.put("H.WHRL", "whirlpool"); descMap.put("H.WHRL", "a turbulent, rotating movement of water in a stream");
        titleMap.put("H.WLL", "well"); descMap.put("H.WLL", "a cylindrical hole, pit, or tunnel drilled or dug down to a depth from which water, oil, or gas can be pumped or brought to the surface");
        titleMap.put("H.WLLQ", "abandoned well"); descMap.put("H.WLLQ","");
        titleMap.put("H.WLLS", "wells"); descMap.put("H.WLLS", "cylindrical holes, pits, or tunnels drilled or dug down to a depth from which water, oil, or gas can be pumped or brought to the surface");
        titleMap.put("H.WTLD", "wetland"); descMap.put("H.WTLD", "an area subject to inundation, usually characterized by bog, marsh, or swamp vegetation");
        titleMap.put("H.WTLDI", "intermittent wetland"); descMap.put("H.WTLDI","");
        titleMap.put("H.WTRC", "watercourse"); descMap.put("H.WTRC", "a natural, well-defined channel produced by flowing water, or an artificial channel designed to carry flowing water");
        titleMap.put("H.WTRH", "waterhole(s)"); descMap.put("H.WTRH", "a natural hole, hollow, or small depression that contains water, used by man and animals, especially in arid areas");
        titleMap.put("L.AGRC", "agricultural colony"); descMap.put("L.AGRC", "a tract of land set aside for agricultural settlement");
        titleMap.put("L.AMUS", "amusement park"); descMap.put("L.AMUS", "Amusement Park are theme parks, adventure parks offering entertainment, similar to funfairs but with a fix location");
        titleMap.put("L.AREA", "area"); descMap.put("L.AREA", "a tract of land without homogeneous character or boundaries");
        titleMap.put("L.BSND", "drainage basin"); descMap.put("L.BSND", "an area drained by a stream");
        titleMap.put("L.BSNP", "petroleum basin"); descMap.put("L.BSNP", "an area underlain by an oil-rich structural basin");
        titleMap.put("L.BTL", "battlefield"); descMap.put("L.BTL", "a site of a land battle of historical importance");
        titleMap.put("L.CLG", "clearing"); descMap.put("L.CLG", "an area in a forest with trees removed");
        titleMap.put("L.CMN", "common"); descMap.put("L.CMN", "a park or pasture for community use");
        titleMap.put("L.CNS", "concession area"); descMap.put("L.CNS", "a lease of land by a government for economic development, e.g., mining, forestry");
        titleMap.put("L.COLF", "coalfield"); descMap.put("L.COLF", "a region in which coal deposits of possible economic value occur");
        titleMap.put("L.CONT", "continent"); descMap.put("L.CONT", "continent: Europe, Africa, Asia, North America, South America, Oceania, Antarctica");
        titleMap.put("L.CST", "coast"); descMap.put("L.CST", "a zone of variable width straddling the shoreline");
        titleMap.put("L.CTRB", "business center"); descMap.put("L.CTRB", "a place where a number of businesses are located");
        titleMap.put("L.DEVH", "housing development"); descMap.put("L.DEVH", "a tract of land on which many houses of similar design are built according to a development plan");
        titleMap.put("L.FLD", "field(s)"); descMap.put("L.FLD", "an open as opposed to wooded area");
        titleMap.put("L.FLDI", "irrigated field(s)"); descMap.put("L.FLDI", "a tract of level or terraced land which is irrigated");
        titleMap.put("L.GASF", "gasfield"); descMap.put("L.GASF", "an area containing a subterranean store of natural gas of economic value");
        titleMap.put("L.GRAZ", "grazing area"); descMap.put("L.GRAZ", "an area of grasses and shrubs used for grazing");
        titleMap.put("L.GVL", "gravel area"); descMap.put("L.GVL", "an area covered with gravel");
        titleMap.put("L.INDS", "industrial area"); descMap.put("L.INDS", "an area characterized by industrial activity");
        titleMap.put("L.LAND", "arctic land"); descMap.put("L.LAND", "a tract of land in the Arctic");
        titleMap.put("L.LCTY", "locality"); descMap.put("L.LCTY", "a minor area or place of unspecified or mixed character and indefinite boundaries");
        titleMap.put("L.MILB", "military base"); descMap.put("L.MILB", "a place used by an army or other armed service for storing arms and supplies, and for accommodating and training troops, a base from which operations can be initiated");
        titleMap.put("L.MNA", "mining area"); descMap.put("L.MNA", "an area of mine sites where minerals and ores are extracted");
        titleMap.put("L.MVA", "maneuver area"); descMap.put("L.MVA", "a tract of land where military field exercises are carried out");
        titleMap.put("L.NVB", "naval base"); descMap.put("L.NVB", "an area used to store supplies, provide barracks for troops and naval personnel, a port for naval vessels, and from which operations are initiated");
        titleMap.put("L.OAS", "oasis(-es)"); descMap.put("L.OAS", "an area in a desert made productive by the availability of water");
        titleMap.put("L.OILF", "oilfield"); descMap.put("L.OILF", "an area containing a subterranean store of petroleum of economic value");
        titleMap.put("L.PEAT", "peat cutting area"); descMap.put("L.PEAT", "an area where peat is harvested");
        titleMap.put("L.PRK", "park"); descMap.put("L.PRK", "an area, often of forested land, maintained as a place of beauty, or for recreation");
        titleMap.put("L.PRT", "port"); descMap.put("L.PRT", "a place provided with terminal and transfer facilities for loading and discharging waterborne cargo or passengers, usually located in a harbor");
        titleMap.put("L.QCKS", "quicksand"); descMap.put("L.QCKS", "an area where loose sand with water moving through it may become unstable when heavy objects are placed at the surface, causing them to sink");
        titleMap.put("L.RES", "reserve"); descMap.put("L.RES", "a tract of public land reserved for future use or restricted as to use");
        titleMap.put("L.RESA", "agricultural reserve"); descMap.put("L.RESA", "a tract of land reserved for agricultural reclamation and/or development");
        titleMap.put("L.RESF", "forest reserve"); descMap.put("L.RESF", "a forested area set aside for preservation or controlled use");
        titleMap.put("L.RESH", "hunting reserve"); descMap.put("L.RESH", "a tract of land used primarily for hunting");
        titleMap.put("L.RESN", "nature reserve"); descMap.put("L.RESN", "an area reserved for the maintenance of a natural habitat");
        titleMap.put("L.RESP", "palm tree reserve"); descMap.put("L.RESP", "an area of palm trees where use is controlled");
        titleMap.put("L.RESV", "reservation"); descMap.put("L.RESV", "a tract of land set aside for aboriginal, tribal, or native populations");
        titleMap.put("L.RESW", "wildlife reserve"); descMap.put("L.RESW", "a tract of public land reserved for the preservation of wildlife");
        titleMap.put("L.RGN", "region"); descMap.put("L.RGN", "an area distinguished by one or more observable physical or cultural characteristics");
        titleMap.put("L.RGNE", "economic region"); descMap.put("L.RGNE", "a region of a country established for economic development or for statistical purposes");
        titleMap.put("L.RGNH", "historical region"); descMap.put("L.RGNH", "a former historic area distinguished by one or more observable physical or cultural characteristics");
        titleMap.put("L.RGNL", "lake region"); descMap.put("L.RGNL", "a tract of land distinguished by numerous lakes");
        titleMap.put("L.RNGA", "artillery range"); descMap.put("L.RNGA", "a tract of land used for artillery firing practice");
        titleMap.put("L.SALT", "salt area"); descMap.put("L.SALT", "a shallow basin or flat where salt accumulates after periodic inundation");
        titleMap.put("L.SNOW", "snowfield"); descMap.put("L.SNOW", "an area of permanent snow and ice forming the accumulation area of a glacier");
        titleMap.put("L.TRB", "tribal area"); descMap.put("L.TRB", "a tract of land used by nomadic or other tribes");
        titleMap.put("P.PPL", "populated place"); descMap.put("P.PPL", "a city, town, village, or other agglomeration of buildings where people live and work");
        titleMap.put("P.PPLA", "seat of a first-order administrative division"); descMap.put("P.PPLA", "seat of a first-order administrative division (PPLC takes precedence over PPLA)");
        titleMap.put("P.PPLA2", "seat of a second-order administrative division"); descMap.put("P.PPLA2","");
        titleMap.put("P.PPLA3", "seat of a third-order administrative division"); descMap.put("P.PPLA3","");
        titleMap.put("P.PPLA4", "seat of a fourth-order administrative division"); descMap.put("P.PPLA4","");
        titleMap.put("P.PPLC", "capital of a political entity"); descMap.put("P.PPLC","");
        titleMap.put("P.PPLCH", "historical capital of a political entity"); descMap.put("P.PPLCH", "a former capital of a political entity");
        titleMap.put("P.PPLF", "farm village"); descMap.put("P.PPLF", "a populated place where the population is largely engaged in agricultural activities");
        titleMap.put("P.PPLG", "seat of government of a political entity"); descMap.put("P.PPLG","");
        titleMap.put("P.PPLH", "historical populated place"); descMap.put("P.PPLH", "a populated place that no longer exists");
        titleMap.put("P.PPLL", "populated locality"); descMap.put("P.PPLL", "an area similar to a locality but with a small group of dwellings or other buildings");
        titleMap.put("P.PPLQ", "abandoned populated place"); descMap.put("P.PPLQ","");
        titleMap.put("P.PPLR", "religious populated place"); descMap.put("P.PPLR", "a populated place whose population is largely engaged in religious occupations");
        titleMap.put("P.PPLS", "populated places"); descMap.put("P.PPLS", "cities, towns, villages, or other agglomerations of buildings where people live and work");
        titleMap.put("P.PPLW", "destroyed populated place"); descMap.put("P.PPLW", "a village, town or city destroyed by a natural disaster, or by war");
        titleMap.put("P.PPLX", "section of populated place"); descMap.put("P.PPLX","");
        titleMap.put("P.STLMT", "israeli settlement"); descMap.put("P.STLMT","");
        titleMap.put("R.CSWY", "causeway"); descMap.put("R.CSWY", "a raised roadway across wet ground or shallow water");
        titleMap.put("R.OILP", "oil pipeline"); descMap.put("R.OILP", "a pipeline used for transporting oil");
        titleMap.put("R.PRMN", "promenade"); descMap.put("R.PRMN", "a place for public walking, usually along a beach front");
        titleMap.put("R.PTGE", "portage"); descMap.put("R.PTGE", "a place where boats, goods, etc., are carried overland between navigable waters");
        titleMap.put("R.RD", "road"); descMap.put("R.RD", "an open way with improved surface for transportation of animals, people and vehicles");
        titleMap.put("R.RDA", "ancient road"); descMap.put("R.RDA", "the remains of a road used by ancient cultures");
        titleMap.put("R.RDB", "road bend"); descMap.put("R.RDB", "a conspicuously curved or bent section of a road");
        titleMap.put("R.RDCUT", "road cut"); descMap.put("R.RDCUT", "an excavation cut through a hill or ridge for a road");
        titleMap.put("R.RDJCT", "road junction"); descMap.put("R.RDJCT", "a place where two or more roads join");
        titleMap.put("R.RJCT", "railroad junction"); descMap.put("R.RJCT", "a place where two or more railroad tracks join");
        titleMap.put("R.RR", "railroad"); descMap.put("R.RR", "a permanent twin steel-rail track on which freight and passenger cars move long distances");
        titleMap.put("R.RRQ", "abandoned railroad"); descMap.put("R.RRQ","");
        titleMap.put("R.RTE", "caravan route"); descMap.put("R.RTE", "the route taken by caravans");
        titleMap.put("R.RYD", "railroad yard"); descMap.put("R.RYD", "a system of tracks used for the making up of trains, and switching and storing freight cars");
        titleMap.put("R.ST", "street"); descMap.put("R.ST", "a paved urban thoroughfare");
        titleMap.put("R.STKR", "stock route"); descMap.put("R.STKR", "a route taken by livestock herds");
        titleMap.put("R.TNL", "tunnel"); descMap.put("R.TNL", "a subterranean passageway for transportation");
        titleMap.put("R.TNLN", "natural tunnel"); descMap.put("R.TNLN", "a cave that is open at both ends");
        titleMap.put("R.TNLRD", "road tunnel"); descMap.put("R.TNLRD", "a tunnel through which a road passes");
        titleMap.put("R.TNLRR", "railroad tunnel"); descMap.put("R.TNLRR", "a tunnel through which a railroad passes");
        titleMap.put("R.TNLS", "tunnels"); descMap.put("R.TNLS", "subterranean passageways for transportation");
        titleMap.put("R.TRL", "trail"); descMap.put("R.TRL", "a path, track, or route used by pedestrians, animals, or off-road vehicles");
        titleMap.put("S.ADMF", "administrative facility"); descMap.put("S.ADMF", "a government building");
        titleMap.put("S.AGRF", "agricultural facility"); descMap.put("S.AGRF", "a building and/or tract of land used for improving agriculture");
        titleMap.put("S.AIRB", "airbase"); descMap.put("S.AIRB", "an area used to store supplies, provide barracks for air force personnel, hangars and runways for aircraft, and from which operations are initiated");
        titleMap.put("S.AIRF", "airfield"); descMap.put("S.AIRF", "a place on land where aircraft land and take off; no facilities provided for the commercial handling of passengers and cargo");
        titleMap.put("S.AIRH", "heliport"); descMap.put("S.AIRH", "a place where helicopters land and take off");
        titleMap.put("S.AIRP", "airport"); descMap.put("S.AIRP", "a place where aircraft regularly land and take off, with runways, navigational aids, and major facilities for the commercial handling of passengers and cargo");
        titleMap.put("S.AIRQ", "abandoned airfield"); descMap.put("S.AIRQ","");
        titleMap.put("S.AMTH", "amphitheater"); descMap.put("S.AMTH", "an oval or circular structure with rising tiers of seats about a stage or open space");
        titleMap.put("S.ANS", "ancient site"); descMap.put("S.ANS", "a place where archeological remains, old structures, or cultural artifacts are located");
        titleMap.put("S.AQC", "aquaculture facility"); descMap.put("S.AQC", "facility or area for the cultivation of aquatic animals and plants, especially fish, shellfish, and seaweed, in natural or controlled marine or freshwater environments; underwater agriculture");
        titleMap.put("S.ARCH", "arch"); descMap.put("S.ARCH", "a natural or man-made structure in the form of an arch");
        titleMap.put("S.ASTR", "astronomical station"); descMap.put("S.ASTR", "a point on the earth whose position has been determined by observations of celestial bodies");
        titleMap.put("S.ASYL", "asylum"); descMap.put("S.ASYL", "a facility where the insane are cared for and protected");
        titleMap.put("S.ATHF", "athletic field"); descMap.put("S.ATHF", "a tract of land used for playing team sports, and athletic track and field events");
        titleMap.put("S.ATM", "automatic teller machine"); descMap.put("S.ATM", "An unattended electronic machine in a public place, connected to a data system and related equipment and activated by a bank customer to obtain cash withdrawals and other banking services.");
        titleMap.put("S.BANK", "bank"); descMap.put("S.BANK", "A business establishment in which money is kept for saving or commercial purposes or is invested, supplied for loans, or exchanged.");
        titleMap.put("S.BCN", "beacon"); descMap.put("S.BCN", "a fixed artificial navigation mark");
        titleMap.put("S.BDG", "bridge"); descMap.put("S.BDG", "a structure erected across an obstacle such as a stream, road, etc., in order to carry roads, railroads, and pedestrians across");
        titleMap.put("S.BDGQ", "ruined bridge"); descMap.put("S.BDGQ", "a destroyed or decayed bridge which is no longer functional");
        titleMap.put("S.BLDG", "building(s)"); descMap.put("S.BLDG", "a structure built for permanent use, as a house, factory, etc.");
        titleMap.put("S.BLDO", "office building"); descMap.put("S.BLDO", "commercial building where business and/or services are conducted");
        titleMap.put("S.BP", "boundary marker"); descMap.put("S.BP", "a fixture marking a point along a boundary");
        titleMap.put("S.BRKS", "barracks"); descMap.put("S.BRKS", "a building for lodging military personnel");
        titleMap.put("S.BRKW", "breakwater"); descMap.put("S.BRKW", "a structure erected to break the force of waves at the entrance to a harbor or port");
        titleMap.put("S.BSTN", "baling station"); descMap.put("S.BSTN", "a facility for baling agricultural products");
        titleMap.put("S.BTYD", "boatyard"); descMap.put("S.BTYD", "a waterside facility for servicing, repairing, and building small vessels");
        titleMap.put("S.BUR", "burial cave(s)"); descMap.put("S.BUR", "a cave used for human burials");
        titleMap.put("S.BUSTN", "bus station"); descMap.put("S.BUSTN", "a facility comprising ticket office, platforms, etc. for loading and unloading passengers");
        titleMap.put("S.BUSTP", "bus stop"); descMap.put("S.BUSTP", "a place lacking station facilities");
        titleMap.put("S.CARN", "cairn"); descMap.put("S.CARN", "a heap of stones erected as a landmark or for other purposes");
        titleMap.put("S.CAVE", "cave(s)"); descMap.put("S.CAVE", "an underground passageway or chamber, or cavity on the side of a cliff");
        titleMap.put("S.CH", "church"); descMap.put("S.CH", "a building for public Christian worship");
        titleMap.put("S.CMP", "camp(s)"); descMap.put("S.CMP", "a site occupied by tents, huts, or other shelters for temporary use");
        titleMap.put("S.CMPL", "logging camp"); descMap.put("S.CMPL", "a camp used by loggers");
        titleMap.put("S.CMPLA", "labor camp"); descMap.put("S.CMPLA", "a camp used by migrant or temporary laborers");
        titleMap.put("S.CMPMN", "mining camp"); descMap.put("S.CMPMN", "a camp used by miners");
        titleMap.put("S.CMPO", "oil camp"); descMap.put("S.CMPO", "a camp used by oilfield workers");
        titleMap.put("S.CMPQ", "abandoned camp"); descMap.put("S.CMPQ","");
        titleMap.put("S.CMPRF", "refugee camp"); descMap.put("S.CMPRF", "a camp used by refugees");
        titleMap.put("S.CMTY", "cemetery"); descMap.put("S.CMTY", "a burial place or ground");
        titleMap.put("S.COMC", "communication center"); descMap.put("S.COMC", "a facility, including buildings, antennae, towers and electronic equipment for receiving and transmitting information");
        titleMap.put("S.CRRL", "corral(s)"); descMap.put("S.CRRL", "a pen or enclosure for confining or capturing animals");
        titleMap.put("S.CSNO", "casino"); descMap.put("S.CSNO", "a building used for entertainment, especially gambling");
        titleMap.put("S.CSTL", "castle"); descMap.put("S.CSTL", "a large fortified building or set of buildings");
        titleMap.put("S.CSTM", "customs house"); descMap.put("S.CSTM", "a building in a port where customs and duties are paid, and where vessels are entered and cleared");
        titleMap.put("S.CTHSE", "courthouse"); descMap.put("S.CTHSE", "a building in which courts of law are held");
        titleMap.put("S.CTRA", "atomic center"); descMap.put("S.CTRA", "a facility where atomic research is carried out");
        titleMap.put("S.CTRCM", "community center"); descMap.put("S.CTRCM", "a facility for community recreation and other activities");
        titleMap.put("S.CTRF", "facility center"); descMap.put("S.CTRF", "a place where more than one facility is situated");
        titleMap.put("S.CTRM", "medical center"); descMap.put("S.CTRM", "a complex of health care buildings including two or more of the following: hospital, medical school, clinic, pharmacy, doctor's offices, etc.");
        titleMap.put("S.CTRR", "religious center"); descMap.put("S.CTRR", "a facility where more than one religious activity is carried out, e.g., retreat, school, monastery, worship");
        titleMap.put("S.CTRS", "space center"); descMap.put("S.CTRS", "a facility for launching, tracking, or controlling satellites and space vehicles");
        titleMap.put("S.CVNT", "convent"); descMap.put("S.CVNT", "a building where a community of nuns lives in seclusion");
        titleMap.put("S.DAM", "dam"); descMap.put("S.DAM", "a barrier constructed across a stream to impound water");
        titleMap.put("S.DAMQ", "ruined dam"); descMap.put("S.DAMQ", "a destroyed or decayed dam which is no longer functional");
        titleMap.put("S.DAMSB", "sub-surface dam"); descMap.put("S.DAMSB", "a dam put down to bedrock in a sand river");
        titleMap.put("S.DARY", "dairy"); descMap.put("S.DARY", "a facility for the processing, sale and distribution of milk or milk products");
        titleMap.put("S.DCKD", "dry dock"); descMap.put("S.DCKD", "a dock providing support for a vessel, and means for removing the water so that the bottom of the vessel can be exposed");
        titleMap.put("S.DCKY", "dockyard"); descMap.put("S.DCKY", "a facility for servicing, building, or repairing ships");
        titleMap.put("S.DIKE", "dike"); descMap.put("S.DIKE", "an earth or stone embankment usually constructed for flood or stream control");
        titleMap.put("S.DIP", "diplomatic facility"); descMap.put("S.DIP", "office, residence, or facility of a foreign government, which may include an embassy, consulate, chancery, office of charge d'affaires, or other diplomatic, economic, military, or cultural mission");
        titleMap.put("S.DPOF", "fuel depot"); descMap.put("S.DPOF", "an area where fuel is stored");
        titleMap.put("S.EST", "estate(s)"); descMap.put("S.EST", "a large commercialized agricultural landholding with associated buildings and other facilities");
        titleMap.put("S.ESTO", "oil palm plantation"); descMap.put("S.ESTO", "an estate specializing in the cultivation of oil palm trees");
        titleMap.put("S.ESTR", "rubber plantation"); descMap.put("S.ESTR", "an estate which specializes in growing and tapping rubber trees");
        titleMap.put("S.ESTSG", "sugar plantation"); descMap.put("S.ESTSG", "an estate that specializes in growing sugar cane");
        titleMap.put("S.ESTT", "tea plantation"); descMap.put("S.ESTT", "an estate which specializes in growing tea bushes");
        titleMap.put("S.ESTX", "section of estate"); descMap.put("S.ESTX\"","");
        titleMap.put("S.FCL", "facility"); descMap.put("S.FCL", "a building or buildings housing a center, institute, foundation, hospital, prison, mission, courthouse, etc.");
        titleMap.put("S.FNDY", "foundry"); descMap.put("S.FNDY", "a building or works where metal casting is carried out");
        titleMap.put("S.FRM", "farm"); descMap.put("S.FRM", "a tract of land with associated buildings devoted to agriculture");
        titleMap.put("S.FRMQ", "abandoned farm"); descMap.put("S.FRMQ","");
        titleMap.put("S.FRMS", "farms"); descMap.put("S.FRMS", "tracts of land with associated buildings devoted to agriculture");
        titleMap.put("S.FRMT", "farmstead"); descMap.put("S.FRMT", "the buildings and adjacent service areas of a farm");
        titleMap.put("S.FT", "fort"); descMap.put("S.FT", "a defensive structure or earthworks");
        titleMap.put("S.FY", "ferry"); descMap.put("S.FY", "a boat or other floating conveyance and terminal facilities regularly used to transport people and vehicles across a waterbody");
        titleMap.put("S.GATE", "gate"); descMap.put("S.GATE", "a controlled access entrance or exit");
        titleMap.put("S.GDN", "garden(s)"); descMap.put("S.GDN", "an enclosure for displaying selected plant or animal life");
        titleMap.put("S.GHAT", "ghat"); descMap.put("S.GHAT", "a set of steps leading to a river, which are of religious significance, and at their base is usually a platform for bathing");
        titleMap.put("S.GHSE", "guest house"); descMap.put("S.GHSE", "a house used to provide lodging for paying guests");
        titleMap.put("S.GOSP", "gas-oil separator plant"); descMap.put("S.GOSP", "a facility for separating gas from oil");
        titleMap.put("S.GOVL", "local government office"); descMap.put("S.GOVL", "a facility housing local governmental offices, usually a city, town, or village hall");
        titleMap.put("S.GRVE", "grave"); descMap.put("S.GRVE", "a burial site");
        titleMap.put("S.HERM", "hermitage"); descMap.put("S.HERM", "a secluded residence, usually for religious sects");
        titleMap.put("S.HLT", "halting place"); descMap.put("S.HLT", "a place where caravans stop for rest");
        titleMap.put("S.HMSD", "homestead"); descMap.put("S.HMSD", "a residence, owner's or manager's, on a sheep or cattle station, woolshed, outcamp, or Aboriginal outstation, specific to Australia and New Zealand");
        titleMap.put("S.HSE", "house(s)"); descMap.put("S.HSE", "a building used as a human habitation");
        titleMap.put("S.HSEC", "country house"); descMap.put("S.HSEC", "a large house, mansion, or chateau, on a large estate");
        titleMap.put("S.HSP", "hospital"); descMap.put("S.HSP", "a building in which sick or injured, especially those confined to bed, are medically treated");
        titleMap.put("S.HSPC", "clinic"); descMap.put("S.HSPC", "a medical facility associated with a hospital for outpatients");
        titleMap.put("S.HSPD", "dispensary"); descMap.put("S.HSPD", "a building where medical or dental aid is dispensed");
        titleMap.put("S.HSPL", "leprosarium"); descMap.put("S.HSPL", "an asylum or hospital for lepers");
        titleMap.put("S.HSTS", "historical site"); descMap.put("S.HSTS", "a place of historical importance");
        titleMap.put("S.HTL", "hotel"); descMap.put("S.HTL", "a building providing lodging and/or meals for the public");
        titleMap.put("S.HUT", "hut"); descMap.put("S.HUT", "a small primitive house");
        titleMap.put("S.HUTS", "huts"); descMap.put("S.HUTS", "small primitive houses");
        titleMap.put("S.INSM", "military installation"); descMap.put("S.INSM", "a facility for use of and control by armed forces");
        titleMap.put("S.ITTR", "research institute"); descMap.put("S.ITTR", "a facility where research is carried out");
        titleMap.put("S.JTY", "jetty"); descMap.put("S.JTY", "a structure built out into the water at a river mouth or harbor entrance to regulate currents and silting");
        titleMap.put("S.LDNG", "landing"); descMap.put("S.LDNG", "a place where boats receive or discharge passengers and freight, but lacking most port facilities");
        titleMap.put("S.LEPC", "leper colony"); descMap.put("S.LEPC", "a settled area inhabited by lepers in relative isolation");
        titleMap.put("S.LIBR", "library"); descMap.put("S.LIBR", "A place in which information resources such as books are kept for reading, reference, or lending.");
        titleMap.put("S.LNDF", "landfill"); descMap.put("S.LNDF", "a place for trash and garbage disposal in which the waste is buried between layers of earth to build up low-lying land");
        titleMap.put("S.LOCK", "lock(s)"); descMap.put("S.LOCK", "a basin in a waterway with gates at each end by means of which vessels are passed from one water level to another");
        titleMap.put("S.LTHSE", "lighthouse"); descMap.put("S.LTHSE", "a distinctive structure exhibiting a major navigation light");
        titleMap.put("S.MALL", "mall"); descMap.put("S.MALL", "A large, often enclosed shopping complex containing various stores, businesses, and restaurants usually accessible by common passageways.");
        titleMap.put("S.MAR", "marina"); descMap.put("S.MAR", "a harbor facility for small boats, yachts, etc.");
        titleMap.put("S.MFG", "factory"); descMap.put("S.MFG", "one or more buildings where goods are manufactured, processed or fabricated");
        titleMap.put("S.MFGB", "brewery"); descMap.put("S.MFGB", "one or more buildings where beer is brewed");
        titleMap.put("S.MFGC", "cannery"); descMap.put("S.MFGC", "a building where food items are canned");
        titleMap.put("S.MFGCU", "copper works"); descMap.put("S.MFGCU", "a facility for processing copper ore");
        titleMap.put("S.MFGLM", "limekiln"); descMap.put("S.MFGLM", "a furnace in which limestone is reduced to lime");
        titleMap.put("S.MFGM", "munitions plant"); descMap.put("S.MFGM", "a factory where ammunition is made");
        titleMap.put("S.MFGPH", "phosphate works"); descMap.put("S.MFGPH", "a facility for producing fertilizer");
        titleMap.put("S.MFGQ", "abandoned factory"); descMap.put("S.MFGQ","");
        titleMap.put("S.MFGSG", "sugar refinery"); descMap.put("S.MFGSG", "a facility for converting raw sugar into refined sugar");
        titleMap.put("S.MKT", "market"); descMap.put("S.MKT", "a place where goods are bought and sold at regular intervals");
        titleMap.put("S.ML", "mill(s)"); descMap.put("S.ML", "a building housing machines for transforming, shaping, finishing, grinding, or extracting products");
        titleMap.put("S.MLM", "ore treatment plant"); descMap.put("S.MLM", "a facility for improving the metal content of ore by concentration");
        titleMap.put("S.MLO", "olive oil mill"); descMap.put("S.MLO", "a mill where oil is extracted from olives");
        titleMap.put("S.MLSG", "sugar mill"); descMap.put("S.MLSG", "a facility where sugar cane is processed into raw sugar");
        titleMap.put("S.MLSGQ", "former sugar mill"); descMap.put("S.MLSGQ", "a sugar mill no longer used as a sugar mill");
        titleMap.put("S.MLSW", "sawmill"); descMap.put("S.MLSW", "a mill where logs or lumber are sawn to specified shapes and sizes");
        titleMap.put("S.MLWND", "windmill"); descMap.put("S.MLWND", "a mill or water pump powered by wind");
        titleMap.put("S.MLWTR", "water mill"); descMap.put("S.MLWTR", "a mill powered by running water");
        titleMap.put("S.MN", "mine(s)"); descMap.put("S.MN", "a site where mineral ores are extracted from the ground by excavating surface pits and subterranean passages");
        titleMap.put("S.MNAU", "gold mine(s)"); descMap.put("S.MNAU", "a mine where gold ore, or alluvial gold is extracted");
        titleMap.put("S.MNC", "coal mine(s)"); descMap.put("S.MNC", "a mine where coal is extracted");
        titleMap.put("S.MNCR", "chrome mine(s)"); descMap.put("S.MNCR", "a mine where chrome ore is extracted");
        titleMap.put("S.MNCU", "copper mine(s)"); descMap.put("S.MNCU", "a mine where copper ore is extracted");
        titleMap.put("S.MNFE", "iron mine(s)"); descMap.put("S.MNFE", "a mine where iron ore is extracted");
        titleMap.put("S.MNMT", "monument"); descMap.put("S.MNMT", "a commemorative structure or statue");
        titleMap.put("S.MNN", "salt mine(s)"); descMap.put("S.MNN", "a mine from which salt is extracted");
        titleMap.put("S.MNQ", "abandoned mine"); descMap.put("","");
        titleMap.put("S.MNQR", "quarry(-ies)"); descMap.put("S.MNQR", "a surface mine where building stone or gravel and sand, etc. are extracted");
        titleMap.put("S.MOLE", "mole"); descMap.put("S.MOLE", "a massive structure of masonry or large stones serving as a pier or breakwater");
        titleMap.put("S.MSQE", "mosque"); descMap.put("S.MSQE", "a building for public Islamic worship");
        titleMap.put("S.MSSN", "mission"); descMap.put("S.MSSN", "a place characterized by dwellings, school, church, hospital and other facilities operated by a religious group for the purpose of providing charitable services and to propagate religion");
        titleMap.put("S.MSSNQ", "abandoned mission"); descMap.put("","");
        titleMap.put("S.MSTY", "monastery"); descMap.put("S.MSTY", "a building and grounds where a community of monks lives in seclusion");
        titleMap.put("S.MTRO", "metro station"); descMap.put("S.MTRO", "metro station (Underground, Tube, or Metro)");
        titleMap.put("S.MUS", "museum"); descMap.put("S.MUS", "a building where objects of permanent interest in one or more of the arts and sciences are preserved and exhibited");
        titleMap.put("S.NOV", "novitiate"); descMap.put("S.NOV", "a religious house or school where novices are trained");
        titleMap.put("S.NSY", "nursery(-ies)"); descMap.put("S.NSY", "a place where plants are propagated for transplanting or grafting");
        titleMap.put("S.OBPT", "observation point"); descMap.put("S.OBPT", "a wildlife or scenic observation point");
        titleMap.put("S.OBS", "observatory"); descMap.put("S.OBS", "a facility equipped for observation of atmospheric or space phenomena");
        titleMap.put("S.OBSR", "radio observatory"); descMap.put("S.OBSR", "a facility equipped with an array of antennae for receiving radio waves from space");
        titleMap.put("S.OILJ", "oil pipeline junction"); descMap.put("S.OILJ", "a section of an oil pipeline where two or more pipes join together");
        titleMap.put("S.OILQ", "abandoned oil well"); descMap.put("","");
        titleMap.put("S.OILR", "oil refinery"); descMap.put("S.OILR", "a facility for converting crude oil into refined petroleum products");
        titleMap.put("S.OILT", "tank farm"); descMap.put("S.OILT", "a tract of land occupied by large, cylindrical, metal tanks in which oil or liquid petrochemicals are stored");
        titleMap.put("S.OILW", "oil well"); descMap.put("S.OILW", "a well from which oil may be pumped");
        titleMap.put("S.OPRA", "opera house"); descMap.put("S.OPRA", "A theater designed chiefly for the performance of operas.");
        titleMap.put("S.PAL", "palace"); descMap.put("S.PAL", "a large stately house, often a royal or presidential residence");
        titleMap.put("S.PGDA", "pagoda"); descMap.put("S.PGDA", "a tower-like storied structure, usually a Buddhist shrine");
        titleMap.put("S.PIER", "pier"); descMap.put("S.PIER", "a structure built out into navigable water on piles providing berthing for ships and recreation");
        titleMap.put("S.PKLT", "parking lot"); descMap.put("S.PKLT", "an area used for parking vehicles");
        titleMap.put("S.PMPO", "oil pumping station"); descMap.put("S.PMPO", "a facility for pumping oil through a pipeline");
        titleMap.put("S.PMPW", "water pumping station"); descMap.put("S.PMPW", "a facility for pumping water from a major well or through a pipeline");
        titleMap.put("S.PO", "post office"); descMap.put("S.PO", "a public building in which mail is received, sorted and distributed");
        titleMap.put("S.PP", "police post"); descMap.put("S.PP", "a building in which police are stationed");
        titleMap.put("S.PPQ", "abandoned police post"); descMap.put("","");
        titleMap.put("S.PRKGT", "park gate"); descMap.put("S.PRKGT", "a controlled access to a park");
        titleMap.put("S.PRKHQ", "park headquarters"); descMap.put("S.PRKHQ", "a park administrative facility");
        titleMap.put("S.PRN", "prison"); descMap.put("S.PRN", "a facility for confining prisoners");
        titleMap.put("S.PRNJ", "reformatory"); descMap.put("S.PRNJ", "a facility for confining, training, and reforming young law offenders");
        titleMap.put("S.PRNQ", "abandoned prison"); descMap.put("S.PRNQ","");
        titleMap.put("S.PS", "power station"); descMap.put("S.PS", "a facility for generating electric power");
        titleMap.put("S.PSH", "hydroelectric power station"); descMap.put("S.PSH", "a building where electricity is generated from water power");
        titleMap.put("S.PSTB", "border post"); descMap.put("S.PSTB", "a post or station at an international boundary for the regulation of movement of people and goods");
        titleMap.put("S.PSTC", "customs post"); descMap.put("S.PSTC", "a building at an international boundary where customs and duties are paid on goods");
        titleMap.put("S.PSTP", "patrol post"); descMap.put("S.PSTP", "a post from which patrols are sent out");
        titleMap.put("S.PYR", "pyramid"); descMap.put("S.PYR", "an ancient massive structure of square ground plan with four triangular faces meeting at a point and used for enclosing tombs");
        titleMap.put("S.PYRS", "pyramids"); descMap.put("S.PYRS", "ancient massive structures of square ground plan with four triangular faces meeting at a point and used for enclosing tombs");
        titleMap.put("S.QUAY", "quay"); descMap.put("S.QUAY", "a structure of solid construction along a shore or bank which provides berthing for ships and which generally provides cargo handling facilities");
        titleMap.put("S.RDCR", "traffic circle"); descMap.put("S.RDCR", "a road junction formed around a central circle about which traffic moves in one direction only");
        titleMap.put("S.RECG", "golf course"); descMap.put("S.RECG", "a recreation field where golf is played");
        titleMap.put("S.RECR", "racetrack"); descMap.put("S.RECR", "a track where races are held");
        titleMap.put("S.REST", "restaurant"); descMap.put("S.REST", "A place where meals are served to the public");
        titleMap.put("S.RET", "store"); descMap.put("S.RET", "a building where goods and/or services are offered for sale");
        titleMap.put("S.RHSE", "resthouse"); descMap.put("S.RHSE", "a structure maintained for the rest and shelter of travelers");
        titleMap.put("S.RKRY", "rookery"); descMap.put("S.RKRY", "a breeding place of a colony of birds or seals");
        titleMap.put("S.RLG", "religious site"); descMap.put("S.RLG", "an ancient site of significant religious importance");
        titleMap.put("S.RLGR", "retreat"); descMap.put("S.RLGR", "a place of temporary seclusion, especially for religious groups");
        titleMap.put("S.RNCH", "ranch(es)"); descMap.put("S.RNCH", "a large farm specializing in extensive grazing of livestock");
        titleMap.put("S.RSD", "railroad siding"); descMap.put("S.RSD", "a short track parallel to and joining the main track");
        titleMap.put("S.RSGNL", "railroad signal"); descMap.put("S.RSGNL", "a signal at the entrance of a particular section of track governing the movement of trains");
        titleMap.put("S.RSRT", "resort"); descMap.put("S.RSRT", "a specialized facility for vacation, health, or participation sports activities");
        titleMap.put("S.RSTN", "railroad station"); descMap.put("S.RSTN", "a facility comprising ticket office, platforms, etc. for loading and unloading train passengers and freight");
        titleMap.put("S.RSTNQ", "abandoned railroad station"); descMap.put("S.RSTNQ","");
        titleMap.put("S.RSTP", "railroad stop"); descMap.put("S.RSTP", "a place lacking station facilities where trains stop to pick up and unload passengers and freight");
        titleMap.put("S.RSTPQ", "abandoned railroad stop"); descMap.put("S.RSTPQ","");
        titleMap.put("S.RUIN", "ruin(s)"); descMap.put("S.RUIN", "a destroyed or decayed structure which is no longer functional");
        titleMap.put("S.SCH", "school"); descMap.put("S.SCH", "building(s) where instruction in one or more branches of knowledge takes place");
        titleMap.put("S.SCHA", "agricultural school"); descMap.put("S.SCHA", "a school with a curriculum focused on agriculture");
        titleMap.put("S.SCHC", "college"); descMap.put("S.SCHC", "the grounds and buildings of an institution of higher learning");
        titleMap.put("S.SCHL", "language school"); descMap.put("S.SCHL", "Language Schools & Institutions");
        titleMap.put("S.SCHM", "military school"); descMap.put("S.SCHM", "a school at which military science forms the core of the curriculum");
        titleMap.put("S.SCHN", "maritime school"); descMap.put("S.SCHN", "a school at which maritime sciences form the core of the curriculum");
        titleMap.put("S.SCHT", "technical school"); descMap.put("S.SCHT", "post-secondary school with a specifically technical or vocational curriculum");
        titleMap.put("S.SECP", "State Exam Prep Centre"); descMap.put("S.SECP", "state exam preparation centres");
        titleMap.put("S.SHPF", "sheepfold"); descMap.put("S.SHPF", "a fence or wall enclosure for sheep and other small herd animals");
        titleMap.put("S.SHRN", "shrine"); descMap.put("S.SHRN", "a structure or place memorializing a person or religious concept");
        titleMap.put("S.SHSE", "storehouse"); descMap.put("S.SHSE", "a building for storing goods, especially provisions");
        titleMap.put("S.SLCE", "sluice"); descMap.put("S.SLCE", "a conduit or passage for carrying off surplus water from a waterbody, usually regulated by means of a sluice gate");
        titleMap.put("S.SNTR", "sanatorium"); descMap.put("S.SNTR", "a facility where victims of physical or mental disorders are treated");
        titleMap.put("S.SPA", "spa"); descMap.put("S.SPA", "a resort area usually developed around a medicinal spring");
        titleMap.put("S.SPLY", "spillway"); descMap.put("S.SPLY", "a passage or outlet through which surplus water flows over, around or through a dam");
        titleMap.put("S.SQR", "square"); descMap.put("S.SQR", "a broad, open, public area near the center of a town or city");
        titleMap.put("S.STBL", "stable"); descMap.put("S.STBL", "a building for the shelter and feeding of farm animals, especially horses");
        titleMap.put("S.STDM", "stadium"); descMap.put("S.STDM", "a structure with an enclosure for athletic games with tiers of seats for spectators");
        titleMap.put("S.STNB", "scientific research base"); descMap.put("S.STNB", "a scientific facility used as a base from which research is carried out or monitored");
        titleMap.put("S.STNC", "coast guard station"); descMap.put("S.STNC", "a facility from which the coast is guarded by armed vessels");
        titleMap.put("S.STNE", "experiment station"); descMap.put("S.STNE", "a facility for carrying out experiments");
        titleMap.put("S.STNF", "forest station"); descMap.put("S.STNF", "a collection of buildings and facilities for carrying out forest management");
        titleMap.put("S.STNI", "inspection station"); descMap.put("S.STNI", "a station at which vehicles, goods, and people are inspected");
        titleMap.put("S.STNM", "meteorological station"); descMap.put("S.STNM", "a station at which weather elements are recorded");
        titleMap.put("S.STNR", "radio station"); descMap.put("S.STNR", "a facility for producing and transmitting information by radio waves");
        titleMap.put("S.STNS", "satellite station"); descMap.put("S.STNS", "a facility for tracking and communicating with orbiting satellites");
        titleMap.put("S.STNW", "whaling station"); descMap.put("S.STNW", "a facility for butchering whales and processing train oil");
        titleMap.put("S.STPS", "steps"); descMap.put("S.STPS", "stones or slabs placed for ease in ascending or descending a steep slope");
        titleMap.put("S.SWT", "sewage treatment plant"); descMap.put("S.SWT", "facility for the processing of sewage and/or wastewater");
        titleMap.put("S.THTR", "theater"); descMap.put("S.THTR", "A building, room, or outdoor structure for the presentation of plays, films, or other dramatic performances");
        titleMap.put("S.TMB", "tomb(s)"); descMap.put("S.TMB", "a structure for interring bodies");
        titleMap.put("S.TMPL", "temple(s)"); descMap.put("S.TMPL", "an edifice dedicated to religious worship");
        titleMap.put("S.TNKD", "cattle dipping tank"); descMap.put("S.TNKD", "a small artificial pond used for immersing cattle in chemically treated water for disease control");
        titleMap.put("S.TOWR", "tower"); descMap.put("S.TOWR", "a high conspicuous structure, typically much higher than its diameter");
        titleMap.put("S.TRANT", "transit terminal"); descMap.put("S.TRANT", "facilities for the handling of vehicular freight and passengers");
        titleMap.put("S.TRIG", "triangulation station"); descMap.put("S.TRIG", "a point on the earth whose position has been determined by triangulation");
        titleMap.put("S.TRMO", "oil pipeline terminal"); descMap.put("S.TRMO", "a tank farm or loading facility at the end of an oil pipeline");
        titleMap.put("S.TWO", "temp work office"); descMap.put("S.TWO", "Temporary Work Offices");
        titleMap.put("S.UNIP", "university prep school"); descMap.put("S.UNIP", "University Preparation Schools & Institutions");
        titleMap.put("S.UNIV", "university"); descMap.put("S.UNIV", "An institution for higher learning with teaching and research facilities constituting a graduate school and professional schools that award master's degrees and doctorates and an undergraduate division that awards bachelor's degrees.");
        titleMap.put("S.USGE", "united states government establishment"); descMap.put("S.USGE", "a facility operated by the United States Government in Panama");
        titleMap.put("S.VETF", "veterinary facility"); descMap.put("S.VETF", "a building or camp at which veterinary services are available");
        titleMap.put("S.WALL", "wall"); descMap.put("S.WALL", "a thick masonry structure, usually enclosing a field or building, or forming the side of a structure");
        titleMap.put("S.WALLA", "ancient wall"); descMap.put("S.WALLA", "the remains of a linear defensive stone structure");
        titleMap.put("S.WEIR", "weir(s)"); descMap.put("S.WEIR", "a small dam in a stream, designed to raise the water level or to divert stream flow through a desired channel");
        titleMap.put("S.WHRF", "wharf(-ves)"); descMap.put("S.WHRF", "a structure of open rather than solid construction along a shore or a bank which provides berthing for ships and cargo-handling facilities");
        titleMap.put("S.WRCK", "wreck"); descMap.put("S.WRCK", "the site of the remains of a wrecked vessel");
        titleMap.put("S.WTRW", "waterworks"); descMap.put("S.WTRW", "a facility for supplying potable water through a water source and a system of pumps and filtration beds");
        titleMap.put("S.ZNF", "free trade zone"); descMap.put("S.ZNF", "an area, usually a section of a port, where goods may be received and shipped free of customs duty and of most customs regulations");
        titleMap.put("S.ZOO", "zoo"); descMap.put("S.ZOO", "a zoological garden or park where wild animals are kept for exhibition");
        titleMap.put("T.ASPH", "asphalt lake"); descMap.put("T.ASPH", "a small basin containing naturally occurring asphalt");
        titleMap.put("T.ATOL", "atoll(s)"); descMap.put("T.ATOL", "a ring-shaped coral reef which has closely spaced islands on it encircling a lagoon");
        titleMap.put("T.BAR", "bar"); descMap.put("T.BAR", "a shallow ridge or mound of coarse unconsolidated material in a stream channel, at the mouth of a stream, estuary, or lagoon and in the wave-break zone along coasts");
        titleMap.put("T.BCH", "beach"); descMap.put("T.BCH", "a shore zone of coarse unconsolidated sediment that extends from the low-water line to the highest reach of storm waves");
        titleMap.put("T.BCHS", "beaches"); descMap.put("T.BCHS", "a shore zone of coarse unconsolidated sediment that extends from the low-water line to the highest reach of storm waves");
        titleMap.put("T.BDLD", "badlands"); descMap.put("T.BDLD", "an area characterized by a maze of very closely spaced, deep, narrow, steep-sided ravines, and sharp crests and pinnacles");
        titleMap.put("T.BLDR", "boulder field"); descMap.put("T.BLDR", "a high altitude or high latitude bare, flat area covered with large angular rocks");
        titleMap.put("T.BLHL", "blowhole(s)"); descMap.put("T.BLHL", "a hole in coastal rock through which sea water is forced by a rising tide or waves and spurted through an outlet into the air");
        titleMap.put("T.BLOW", "blowout(s)"); descMap.put("T.BLOW", "a small depression in sandy terrain, caused by wind erosion");
        titleMap.put("T.BNCH", "bench"); descMap.put("T.BNCH", "a long, narrow bedrock platform bounded by steeper slopes above and below, usually overlooking a waterbody");
        titleMap.put("T.BUTE", "butte(s)"); descMap.put("T.BUTE", "a small, isolated, usually flat-topped hill with steep sides");
        titleMap.put("T.CAPE", "cape"); descMap.put("T.CAPE", "a land area, more prominent than a point, projecting into the sea and marking a notable change in coastal direction");
        titleMap.put("T.CFT", "cleft(s)"); descMap.put("T.CFT", "a deep narrow slot, notch, or groove in a coastal cliff");
        titleMap.put("T.CLDA", "caldera"); descMap.put("T.CLDA", "a depression measuring kilometers across formed by the collapse of a volcanic mountain");
        titleMap.put("T.CLF", "cliff(s)"); descMap.put("T.CLF", "a high, steep to perpendicular slope overlooking a waterbody or lower area");
        titleMap.put("T.CNYN", "canyon"); descMap.put("T.CNYN", "a deep, narrow valley with steep sides cutting into a plateau or mountainous area");
        titleMap.put("T.CONE", "cone(s)"); descMap.put("T.CONE", "a conical landform composed of mud or volcanic material");
        titleMap.put("T.CRDR", "corridor"); descMap.put("T.CRDR", "a strip or area of land having significance as an access way");
        titleMap.put("T.CRQ", "cirque"); descMap.put("T.CRQ", "a bowl-like hollow partially surrounded by cliffs or steep slopes at the head of a glaciated valley");
        titleMap.put("T.CRQS", "cirques"); descMap.put("T.CRQS", "bowl-like hollows partially surrounded by cliffs or steep slopes at the head of a glaciated valley");
        titleMap.put("T.CRTR", "crater(s)"); descMap.put("T.CRTR", "a generally circular saucer or bowl-shaped depression caused by volcanic or meteorite explosive action");
        titleMap.put("T.CUET", "cuesta(s)"); descMap.put("T.CUET", "an asymmetric ridge formed on tilted strata");
        titleMap.put("T.DLTA", "delta"); descMap.put("T.DLTA", "a flat plain formed by alluvial deposits at the mouth of a stream");
        titleMap.put("T.DPR", "depression(s)"); descMap.put("T.DPR", "a low area surrounded by higher land and usually characterized by interior drainage");
        titleMap.put("T.DSRT", "desert"); descMap.put("T.DSRT", "a large area with little or no vegetation due to extreme environmental conditions");
        titleMap.put("T.DUNE", "dune(s)"); descMap.put("T.DUNE", "a wave form, ridge or star shape feature composed of sand");
        titleMap.put("T.DVD", "divide"); descMap.put("T.DVD", "a line separating adjacent drainage basins");
        titleMap.put("T.ERG", "sandy desert"); descMap.put("T.ERG", "an extensive tract of shifting sand and sand dunes");
        titleMap.put("T.FAN", "fan(s)"); descMap.put("T.FAN", "a fan-shaped wedge of coarse alluvium with apex merging with a mountain stream bed and the fan spreading out at a low angle slope onto an adjacent plain");
        titleMap.put("T.FORD", "ford"); descMap.put("T.FORD", "a shallow part of a stream which can be crossed on foot or by land vehicle");
        titleMap.put("T.FSR", "fissure"); descMap.put("T.FSR", "a crack associated with volcanism");
        titleMap.put("T.GAP", "gap"); descMap.put("T.GAP", "a low place in a ridge, not used for transportation");
        titleMap.put("T.GRGE", "gorge(s)"); descMap.put("T.GRGE", "a short, narrow, steep-sided section of a stream valley");
        titleMap.put("T.HDLD", "headland"); descMap.put("T.HDLD", "a high projection of land extending into a large body of water beyond the line of the coast");
        titleMap.put("T.HLL", "hill"); descMap.put("T.HLL", "a rounded elevation of limited extent rising above the surrounding land with local relief of less than 300m");
        titleMap.put("T.HLLS", "hills"); descMap.put("T.HLLS", "rounded elevations of limited extent rising above the surrounding land with local relief of less than 300m");
        titleMap.put("T.HMCK", "hammock(s)"); descMap.put("T.HMCK", "a patch of ground, distinct from and slightly above the surrounding plain or wetland. Often occurs in groups");
        titleMap.put("T.HMDA", "rock desert"); descMap.put("T.HMDA", "a relatively sand-free, high bedrock plateau in a hot desert, with or without a gravel veneer");
        titleMap.put("T.INTF", "interfluve"); descMap.put("T.INTF", "a relatively undissected upland between adjacent stream valleys");
        titleMap.put("T.ISL", "island"); descMap.put("T.ISL", "a tract of land, smaller than a continent, surrounded by water at high water");
        titleMap.put("T.ISLET", "islet"); descMap.put("T.ISLET", "small island, bigger than rock, smaller than island.");
        titleMap.put("T.ISLF", "artificial island"); descMap.put("T.ISLF", "an island created by landfill or diking and filling in a wetland, bay, or lagoon");
        titleMap.put("T.ISLM", "mangrove island"); descMap.put("T.ISLM", "a mangrove swamp surrounded by a waterbody");
        titleMap.put("T.ISLS", "islands"); descMap.put("T.ISLS", "tracts of land, smaller than a continent, surrounded by water at high water");
        titleMap.put("T.ISLT", "land-tied island"); descMap.put("T.ISLT", "a coastal island connected to the mainland by barrier beaches, levees or dikes");
        titleMap.put("T.ISLX", "section of island"); descMap.put("T.ISLX","");
        titleMap.put("T.ISTH", "isthmus"); descMap.put("T.ISTH", "a narrow strip of land connecting two larger land masses and bordered by water");
        titleMap.put("T.KRST", "karst area"); descMap.put("T.KRST", "a distinctive landscape developed on soluble rock such as limestone characterized by sinkholes, caves, disappearing streams, and underground drainage");
        titleMap.put("T.LAVA", "lava area"); descMap.put("T.LAVA", "an area of solidified lava");
        titleMap.put("T.LEV", "levee"); descMap.put("T.LEV", "a natural low embankment bordering a distributary or meandering stream; often built up artificially to control floods");
        titleMap.put("T.MESA", "mesa(s)"); descMap.put("T.MESA", "a flat-topped, isolated elevation with steep slopes on all sides, less extensive than a plateau");
        titleMap.put("T.MND", "mound(s)"); descMap.put("T.MND", "a low, isolated, rounded hill");
        titleMap.put("T.MRN", "moraine"); descMap.put("T.MRN", "a mound, ridge, or other accumulation of glacial till");
        titleMap.put("T.MT", "mountain"); descMap.put("T.MT", "an elevation standing high above the surrounding area with small summit area, steep slopes and local relief of 300m or more");
        titleMap.put("T.MTS", "mountains"); descMap.put("T.MTS", "a mountain range or a group of mountains or high ridges");
        titleMap.put("T.NKM", "meander neck"); descMap.put("T.NKM", "a narrow strip of land between the two limbs of a meander loop at its narrowest point");
        titleMap.put("T.NTK", "nunatak"); descMap.put("T.NTK", "a rock or mountain peak protruding through glacial ice");
        titleMap.put("T.NTKS", "nunataks"); descMap.put("T.NTKS", "rocks or mountain peaks protruding through glacial ice");
        titleMap.put("T.PAN", "pan"); descMap.put("T.PAN", "a near-level shallow, natural depression or basin, usually containing an intermittent lake, pond, or pool");
        titleMap.put("T.PANS", "pans"); descMap.put("T.PANS", "a near-level shallow, natural depression or basin, usually containing an intermittent lake, pond, or pool");
        titleMap.put("T.PASS", "pass"); descMap.put("T.PASS", "a break in a mountain range or other high obstruction, used for transportation from one side to the other [See also gap]");
        titleMap.put("T.PEN", "peninsula"); descMap.put("T.PEN", "an elongate area of land projecting into a body of water and nearly surrounded by water");
        titleMap.put("T.PENX", "section of peninsula"); descMap.put("T.PENX","");
        titleMap.put("T.PK", "peak"); descMap.put("T.PK", "a pointed elevation atop a mountain, ridge, or other hypsographic feature");
        titleMap.put("T.PKS", "peaks"); descMap.put("T.PKS", "pointed elevations atop a mountain, ridge, or other hypsographic features");
        titleMap.put("T.PLAT", "plateau"); descMap.put("T.PLAT", "an elevated plain with steep slopes on one or more sides, and often with incised streams");
        titleMap.put("T.PLATX", "section of plateau"); descMap.put("T.PLATX","");
        titleMap.put("T.PLDR", "polder"); descMap.put("T.PLDR", "an area reclaimed from the sea by diking and draining");
        titleMap.put("T.PLN", "plain(s)"); descMap.put("T.PLN", "an extensive area of comparatively level to gently undulating land, lacking surface irregularities, and usually adjacent to a higher area");
        titleMap.put("T.PLNX", "section of plain"); descMap.put("T.PLNX","");
        titleMap.put("T.PROM", "promontory(-ies)"); descMap.put("T.PROM", "a bluff or prominent hill overlooking or projecting into a lowland");
        titleMap.put("T.PT", "point"); descMap.put("T.PT", "a tapering piece of land projecting into a body of water, less prominent than a cape");
        titleMap.put("T.PTS", "points"); descMap.put("T.PTS", "tapering pieces of land projecting into a body of water, less prominent than a cape");
        titleMap.put("T.RDGB", "beach ridge"); descMap.put("T.RDGB", "a ridge of sand just inland and parallel to the beach, usually in series");
        titleMap.put("T.RDGE", "ridge(s)"); descMap.put("T.RDGE", "a long narrow elevation with steep sides, and a more or less continuous crest");
        titleMap.put("T.REG", "stony desert"); descMap.put("T.REG", "a desert plain characterized by a surface veneer of gravel and stones");
        titleMap.put("T.RK", "rock"); descMap.put("T.RK", "a conspicuous, isolated rocky mass");
        titleMap.put("T.RKFL", "rockfall"); descMap.put("T.RKFL", "an irregular mass of fallen rock at the base of a cliff or steep slope");
        titleMap.put("T.RKS", "rocks"); descMap.put("T.RKS", "conspicuous, isolated rocky masses");
        titleMap.put("T.SAND", "sand area"); descMap.put("T.SAND", "a tract of land covered with sand");
        titleMap.put("T.SBED", "dry stream bed"); descMap.put("T.SBED", "a channel formerly containing the water of a stream");
        titleMap.put("T.SCRP", "escarpment"); descMap.put("T.SCRP", "a long line of cliffs or steep slopes separating level surfaces above and below");
        titleMap.put("T.SDL", "saddle"); descMap.put("T.SDL", "a broad, open pass crossing a ridge or between hills or mountains");
        titleMap.put("T.SHOR", "shore"); descMap.put("T.SHOR", "a narrow zone bordering a waterbody which covers and uncovers at high and low water, respectively");
        titleMap.put("T.SINK", "sinkhole"); descMap.put("T.SINK", "a small crater-shape depression in a karst area");
        titleMap.put("T.SLID", "slide"); descMap.put("T.SLID", "a mound of earth material, at the base of a slope and the associated scoured area");
        titleMap.put("T.SLP", "slope(s)"); descMap.put("T.SLP", "a surface with a relatively uniform slope angle");
        titleMap.put("T.SPIT", "spit"); descMap.put("T.SPIT", "a narrow, straight or curved continuation of a beach into a waterbody");
        titleMap.put("T.SPUR", "spur(s)"); descMap.put("T.SPUR", "a subordinate ridge projecting outward from a hill, mountain or other elevation");
        titleMap.put("T.TAL", "talus slope"); descMap.put("T.TAL", "a steep concave slope formed by an accumulation of loose rock fragments at the base of a cliff or steep slope");
        titleMap.put("T.TRGD", "interdune trough(s)"); descMap.put("T.TRGD", "a long wind-swept trough between parallel longitudinal dunes");
        titleMap.put("T.TRR", "terrace"); descMap.put("T.TRR", "a long, narrow alluvial platform bounded by steeper slopes above and below, usually overlooking a waterbody");
        titleMap.put("T.UPLD", "upland"); descMap.put("T.UPLD", "an extensive interior region of high land with low to moderate surface relief");
        titleMap.put("T.VAL", "valley"); descMap.put("T.VAL", "an elongated depression usually traversed by a stream");
        titleMap.put("T.VALG", "hanging valley"); descMap.put("T.VALG", "a valley the floor of which is notably higher than the valley or shore to which it leads; most common in areas that have been glaciated");
        titleMap.put("T.VALS", "valleys"); descMap.put("T.VALS", "elongated depressions usually traversed by a stream");
        titleMap.put("T.VALX", "section of valley"); descMap.put("T.VALX","");
        titleMap.put("T.VLC", "volcano"); descMap.put("T.VLC", "a conical elevation composed of volcanic materials with a crater at the top");
        titleMap.put("U.APNU", "apron"); descMap.put("U.APNU", "a gentle slope, with a generally smooth surface, particularly found around groups of islands and seamounts");
        titleMap.put("U.ARCU", "arch"); descMap.put("U.ARCU", "a low bulge around the southeastern end of the island of Hawaii");
        titleMap.put("U.ARRU", "arrugado"); descMap.put("U.ARRU", "an area of subdued corrugations off Baja California");
        titleMap.put("U.BDLU", "borderland"); descMap.put("U.BDLU", "a region adjacent to a continent, normally occupied by or bordering a shelf, that is highly irregular with depths well in excess of those typical of a shelf");
        titleMap.put("U.BKSU", "banks"); descMap.put("U.BKSU", "elevations, typically located on a shelf, over which the depth of water is relatively shallow but sufficient for safe surface navigation");
        titleMap.put("U.BNKU", "bank"); descMap.put("U.BNKU", "an elevation, typically located on a shelf, over which the depth of water is relatively shallow but sufficient for safe surface navigation");
        titleMap.put("U.BSNU", "basin"); descMap.put("U.BSNU", "a depression more or less equidimensional in plan and of variable extent");
        titleMap.put("U.CDAU", "cordillera"); descMap.put("U.CDAU", "an entire mountain system including the subordinate ranges, interior plateaus, and basins");
        titleMap.put("U.CNSU", "canyons"); descMap.put("U.CNSU", "relatively narrow, deep depressions with steep sides, the bottom of which generally has a continuous slope");
        titleMap.put("U.CNYU", "canyon"); descMap.put("U.CNYU", "a relatively narrow, deep depression with steep sides, the bottom of which generally has a continuous slope");
        titleMap.put("U.CRSU", "continental rise"); descMap.put("U.CRSU", "a gentle slope rising from oceanic depths towards the foot of a continental slope");
        titleMap.put("U.DEPU", "deep"); descMap.put("U.DEPU", "a localized deep area within the confines of a larger feature, such as a trough, basin or trench");
        titleMap.put("U.EDGU", "shelf edge"); descMap.put("U.EDGU", "a line along which there is a marked increase of slope at the outer margin of a continental shelf or island shelf");
        titleMap.put("U.ESCU", "escarpment (or scarp)"); descMap.put("U.ESCU", "an elongated and comparatively steep slope separating flat or gently sloping areas");
        titleMap.put("U.FANU", "fan"); descMap.put("U.FANU", "a relatively smooth feature normally sloping away from the lower termination of a canyon or canyon system");
        titleMap.put("U.FLTU", "flat"); descMap.put("U.FLTU", "a small level or nearly level area");
        titleMap.put("U.FRZU", "fracture zone"); descMap.put("U.FRZU", "an extensive linear zone of irregular topography of the sea floor, characterized by steep-sided or asymmetrical ridges, troughs, or escarpments");
        titleMap.put("U.FURU", "furrow"); descMap.put("U.FURU", "a closed, linear, narrow, shallow depression");
        titleMap.put("U.GAPU", "gap"); descMap.put("U.GAPU", "a narrow break in a ridge or rise");
        titleMap.put("U.GLYU", "gully"); descMap.put("U.GLYU", "a small valley-like feature");
        titleMap.put("U.HLLU", "hill"); descMap.put("U.HLLU", "an elevation rising generally less than 500 meters");
        titleMap.put("U.HLSU", "hills"); descMap.put("U.HLSU", "elevations rising generally less than 500 meters");
        titleMap.put("U.HOLU", "hole"); descMap.put("U.HOLU", "a small depression of the sea floor");
        titleMap.put("U.KNLU", "knoll"); descMap.put("U.KNLU", "an elevation rising generally more than 500 meters and less than 1,000 meters and of limited extent across the summit");
        titleMap.put("U.KNSU", "knolls"); descMap.put("U.KNSU", "elevations rising generally more than 500 meters and less than 1,000 meters and of limited extent across the summits");
        titleMap.put("U.LDGU", "ledge"); descMap.put("U.LDGU", "a rocky projection or outcrop, commonly linear and near shore");
        titleMap.put("U.LEVU", "levee"); descMap.put("U.LEVU", "an embankment bordering a canyon, valley, or seachannel");
        titleMap.put("U.MESU", "mesa"); descMap.put("U.MESU", "an isolated, extensive, flat-topped elevation on the shelf, with relatively steep sides");
        titleMap.put("U.MNDU", "mound"); descMap.put("U.MNDU", "a low, isolated, rounded hill");
        titleMap.put("U.MOTU", "moat"); descMap.put("U.MOTU", "an annular depression that may not be continuous, located at the base of many seamounts, islands, and other isolated elevations");
        titleMap.put("U.MTU", "mountain"); descMap.put("U.MTU", "a well-delineated subdivision of a large and complex positive feature");
        titleMap.put("U.PKSU", "peaks"); descMap.put("U.PKSU", "prominent elevations, part of a larger feature, either pointed or of very limited extent across the summit");
        titleMap.put("U.PKU", "peak"); descMap.put("U.PKU", "a prominent elevation, part of a larger feature, either pointed or of very limited extent across the summit");
        titleMap.put("U.PLNU", "plain"); descMap.put("U.PLNU", "a flat, gently sloping or nearly level region");
        titleMap.put("U.PLTU", "plateau"); descMap.put("U.PLTU", "a comparatively flat-topped feature of considerable extent, dropping off abruptly on one or more sides");
        titleMap.put("U.PNLU", "pinnacle"); descMap.put("U.PNLU", "a high tower or spire-shaped pillar of rock or coral, alone or cresting a summit");
        titleMap.put("U.PRVU", "province"); descMap.put("U.PRVU", "a region identifiable by a group of similar physiographic features whose characteristics are markedly in contrast with surrounding areas");
        titleMap.put("U.RDGU", "ridge"); descMap.put("U.RDGU", "a long narrow elevation with steep sides");
        titleMap.put("U.RDSU", "ridges"); descMap.put("U.RDSU", "long narrow elevations with steep sides");
        titleMap.put("U.RFSU", "reefs"); descMap.put("U.RFSU", "surface-navigation hazards composed of consolidated material");
        titleMap.put("U.RFU", "reef"); descMap.put("U.RFU", "a surface-navigation hazard composed of consolidated material");
        titleMap.put("U.RISU", "rise"); descMap.put("U.RISU", "a broad elevation that rises gently, and generally smoothly, from the sea floor");
        titleMap.put("U.SCNU", "seachannel"); descMap.put("U.SCNU", "a continuously sloping, elongated depression commonly found in fans or plains and customarily bordered by levees on one or two sides");
        titleMap.put("U.SCSU", "seachannels"); descMap.put("U.SCSU", "continuously sloping, elongated depressions commonly found in fans or plains and customarily bordered by levees on one or two sides");
        titleMap.put("U.SDLU", "saddle"); descMap.put("U.SDLU", "a low part, resembling in shape a saddle, in a ridge or between contiguous seamounts");
        titleMap.put("U.SHFU", "shelf"); descMap.put("U.SHFU", "a zone adjacent to a continent (or around an island) that extends from the low water line to a depth at which there is usually a marked increase of slope towards oceanic depths");
        titleMap.put("U.SHLU", "shoal"); descMap.put("U.SHLU", "a surface-navigation hazard composed of unconsolidated material");
        titleMap.put("U.SHSU", "shoals"); descMap.put("U.SHSU", "hazards to surface navigation composed of unconsolidated material");
        titleMap.put("U.SHVU", "shelf valley"); descMap.put("U.SHVU", "a valley on the shelf, generally the shoreward extension of a canyon");
        titleMap.put("U.SILU", "sill"); descMap.put("U.SILU", "the low part of a gap or saddle separating basins");
        titleMap.put("U.SLPU", "slope"); descMap.put("U.SLPU", "the slope seaward from the shelf edge to the beginning of a continental rise or the point where there is a general reduction in slope");
        titleMap.put("U.SMSU", "seamounts"); descMap.put("U.SMSU", "elevations rising generally more than 1,000 meters and of limited extent across the summit");
        titleMap.put("U.SMU", "seamount"); descMap.put("U.SMU", "an elevation rising generally more than 1,000 meters and of limited extent across the summit");
        titleMap.put("U.SPRU", "spur"); descMap.put("U.SPRU", "a subordinate elevation, ridge, or rise projecting outward from a larger feature");
        titleMap.put("U.TERU", "terrace"); descMap.put("U.TERU", "a relatively flat horizontal or gently inclined surface, sometimes long and narrow, which is bounded by a steeper ascending slope on one side and by a steep descending slope on the opposite side");
        titleMap.put("U.TMSU", "tablemounts (or guyots)"); descMap.put("U.TMSU", "seamounts having a comparatively smooth, flat top");
        titleMap.put("U.TMTU", "tablemount (or guyot)"); descMap.put("U.TMTU", "a seamount having a comparatively smooth, flat top");
        titleMap.put("U.TNGU", "tongue"); descMap.put("U.TNGU", "an elongate (tongue-like) extension of a flat sea floor into an adjacent higher feature");
        titleMap.put("U.TRGU", "trough"); descMap.put("U.TRGU", "a long depression of the sea floor characteristically flat bottomed and steep sided, and normally shallower than a trench");
        titleMap.put("U.TRNU", "trench"); descMap.put("U.TRNU", "a long, narrow, characteristically very deep and asymmetrical depression of the sea floor, with relatively steep sides");
        titleMap.put("U.VALU", "valley"); descMap.put("U.VALU", "a relatively shallow, wide depression, the bottom of which usually has a continuous gradient");
        titleMap.put("U.VLSU", "valleys"); descMap.put("U.VLSU", "a relatively shallow, wide depression, the bottom of which usually has a continuous gradient");
        titleMap.put("V.BUSH", "bush(es)"); descMap.put("V.BUSH", "a small clump of conspicuous bushes in an otherwise bare area");
        titleMap.put("V.CULT", "cultivated area"); descMap.put("V.CULT", "an area under cultivation");
        titleMap.put("V.FRST", "forest(s)"); descMap.put("V.FRST", "an area dominated by tree vegetation");
        titleMap.put("V.FRSTF", "fossilized forest"); descMap.put("V.FRSTF", "a forest fossilized by geologic processes and now exposed at the earth's surface");
        titleMap.put("V.GRSLD", "grassland"); descMap.put("V.GRSLD", "an area dominated by grass vegetation");
        titleMap.put("V.GRVC", "coconut grove"); descMap.put("V.GRVC", "a planting of coconut trees");
        titleMap.put("V.GRVO", "olive grove"); descMap.put("V.GRVO", "a planting of olive trees");
        titleMap.put("V.GRVP", "palm grove"); descMap.put("V.GRVP", "a planting of palm trees");
        titleMap.put("V.GRVPN", "pine grove"); descMap.put("V.GRVPN", "a planting of pine trees");
        titleMap.put("V.HTH", "heath"); descMap.put("V.HTH", "an upland moor or sandy area dominated by low shrubby vegetation including heather");
        titleMap.put("V.MDW", "meadow"); descMap.put("V.MDW", "a small, poorly drained area dominated by grassy vegetation");
        titleMap.put("V.OCH", "orchard(s)"); descMap.put("V.OCH", "a planting of fruit or nut trees");
        titleMap.put("V.SCRB", "scrubland"); descMap.put("V.SCRB", "an area of low trees, bushes, and shrubs stunted by some environmental limitation");
        titleMap.put("V.TREE", "tree(s)"); descMap.put("V.TREE", "a conspicuous tree used as a landmark");
        titleMap.put("V.TUND", "tundra"); descMap.put("V.TUND", "a marshy, treeless, high latitude plain, dominated by mosses, lichens, and low shrub vegetation under permafrost conditions");
        titleMap.put("V.VIN", "vineyard"); descMap.put("V.VIN", "a planting of grapevines");
        titleMap.put("V.VINS", "vineyards	plantings of grapevines"); descMap.put("V.VINS","");
    }

}
